theme = "monokai"

[keys.normal]
C-j = ["extend_to_line_bounds", "delete_selection", "paste_after"]
C-k = ["extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before"]

[editor]
line-number = "relative"
auto-format = true
cursor-shape = { insert = "bar" }
