[[language]]
name = "cpp"
auto-format = true

[[language]]
name = "css"
auto-format = true
formatter = { command = "pnpx", args = ["prettier", "--parser", "css"] }

[[language]]
name = "c"
auto-format = true

[[language]]
name = "c-sharp"
auto-format = true

[[language]]
name = "html"
auto-format = true
formatter = { command = "pnpx", args = ["prettier", "--parser", "html"] }

[[language]]
name = "python"
language-servers = ["pyright"]
auto-format = true
formatter = { command = "black", args = ["-", "--quiet"]}

[language-server.pyright]
command = "pyright-langserver"
args = ["--stdio"]
